# API Configuration Example
# Copy this file to api_config.yaml and fill in your API keys

# Anthropic API configuration
anthropic_api_key: "your_anthropic_api_key_here"
anthropic_model: "claude-3-sonnet-20240229"  # Adjust to latest model as needed

# Model parameters
model_params:
  n_estimators: 100
  max_depth: null  # null for unlimited depth
  random_state: 42
  test_size: 0.2

# AGI probability model parameters
agi_model_params:
  expert_survey_weight: 0.5
  compute_trajectory_weight: 0.5
  economic_impact_threshold: 0.5
  impact_lag_years: 2
  impact_duration_years: 5

# Data configuration
data_cache_dir: "data/raw"
model_save_dir: "data/models"
results_dir: "results"

# Logging
log_level: "INFO"  # Options: DEBUG, INFO, WARNING, ERROR, CRITICAL

# System settings
use_cache: true
current_year: 2025  # Override if needed